schema_version: 1

context:
  name: skipatom
  version: "1.2.5"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/skipatom-${{ version }}.tar.gz
  sha256: 695c7518da994583caf86e01a961d4d13a5d0066a6dcf52c605b90b4f67de410

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - create_cooccurrence_pairs = skipatom.create_cooccurrence_pairs:main
      - create_skipatom_embeddings = skipatom.create_skipatom_embeddings:main
      - create_skipatom_training_data = skipatom.create_skipatom_training_data:main

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - numpy >=1.18.5
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - skipatom
      pip_check: true
      python_version: ${{ python_min }}
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - create_cooccurrence_pairs --help
      - create_skipatom_embeddings --help
      - create_skipatom_training_data --help

about:
  summary: SkipAtom, Distributed representations of atoms, inspired by the Skip-gram model.
  license: MIT
  license_file: LICENSE
  homepage: http://github.com/lantunes/skipatom

extra:
  recipe-maintainers:
    - jan-janssen
